trigger:
  branches:
    include:
      - main  # Trigger pipeline on 'main' branch pushes

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install Dependencies'

- script: npm run build
  displayName: 'Build Backend'

- script: npm test
  displayName: 'Run Tests'  # Run automated tests

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: './dist'  # Replace './dist' with your build folder path
    artifactName: 'drop'
  displayName: 'Publish Build Artifacts'
